apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.cp4iNamespace }}
  project: default
  source:
    path: {{ .Values.cp4iVersion }}
    repoURL: '{{ .Values.spec.source.repoURL }}/cloud-pak-for-integration.git'
    targetRevision: {{ .Values.spec.source.targetRevision }}